server:
  port: 5001

base-url: /data

spring:
  application:
    name: fundAssetsData

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      hibernate:
        engine:
          jdbc:
            spi:
              SqlExceptionHelper: "off"